server:
  port: ${PORT:8081}

spring:
  profiles:
    active: local

  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chronos_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}