server:
  port: ${PORT:8085}

spring:
  profiles:
    active: local

  application:
    name: worker-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:chronos-worker}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

worker:
  id: ${WORKER_ID:worker-local-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  topics:
    execution-dispatch: ${KAFKA_TOPIC_EXECUTION_DISPATCH:execution.dispatch}
    execution-completed: ${KAFKA_TOPIC_EXECUTION_COMPLETED:execution.completed}
    execution-failed: ${KAFKA_TOPIC_EXECUTION_FAILED:execution.failed}
