server:
  port: ${PORT:8084}

spring:
  profiles:
    active: local

  application:
    name: execution-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chronos_job}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:chronos-execution-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true


kafka:
  topics:
    job-triggered: ${KAFKA_TOPIC_JOB_TRIGGERED:job.triggered}
    execution-dispatch: ${KAFKA_TOPIC_EXECUTION_DISPATCH:execution.dispatch}
    execution-completed: ${KAFKA_TOPIC_EXECUTION_COMPLETED:execution.completed}
    execution-failed: ${KAFKA_TOPIC_EXECUTION_FAILED:execution.failed}
    execution-retry: ${KAFKA_TOPIC_EXECUTION_RETRY:execution.retry}
    execution-dlq: ${KAFKA_TOPIC_EXECUTION_DLQ:execution.dlq}

job-service:
  url: ${JOB_SERVICE_URL:http://localhost:8082}
